### ISSUE TITLE
append in prompt does not expand "due:today"

### ISSUE THREAD

**Issue by inducer** [bram85/topydo#103]
If I enter `add blah due:today`, the due date gets expanded.
If I enter `append 42 blah due:today`, the due date does not get expanded.

It feels like it should.

**Comment by mruwek** [comment]
It doesn't expand in CLI-mode either. I don't know however If we really need that expansion as `postpone` does it job just fine. Try `postpone 42 tod`.

**Comment by inducer** [comment]
I agree that it's not totally necessary once you know about `postpone`. Consistency is still valuable though.

**Comment by bram85** [comment]
I think it should, yes.

**Comment by mruwek** [comment]
Isn't it fixed with #129?

**Comment by bram85** [comment]
Indeed, append understands dates and dependencies now.
