### ISSUE TITLE
Overdue due dates should be red

### ISSUE THREAD

**Issue by inducer** [bram85/topydo#104]
(maybe optionally?)

**Comment by bram85** [comment]
Currently I have a `colorblock` branch here on Github which sort of does this (and gradually colors items from green to red as the due date approaches). It is shown as a block before/after the item, not as the font color. Use %z (standard) or %Z (256 colors) in the list format to show such a block:

```
topydo ls -F "%Z %s" 
```

There's still some work to be done in this branch, but I hope to merge it before the next release. I'll look if the font color can also be incorporated somehow.

**Comment by inducer** [comment]
Thanks!

**Comment by bram85** [comment]
Just FYI, overdue tasks are also marked red in the upcoming, new, UI. See this screenshot by @mruwek. Tasks almost due are (gradually) marked light green/yellow/orange. The next release will have this color support (also on the CLI with the example I gave earlier).

https://files.gitter.im/bram85/topydo/xww1/Zrzut-ekranu-z-2016-02-14-23-39-17.png

**Comment by inducer** [comment]
Neat! Where's the code for that?

**Comment by bram85** [comment]
It's in the column-ui branch, which is still work in progress but usable for day to day use. Launch with `topydo columns`,  the shortcuts are 'documented' in topydo.conf in the root folder.

**Comment by bram85** [comment]
Overdue todo items should be visible now in two ways:

* CLI or prompt mode: use the format flag in `ls` to show colors next to each todo using the `%z` placeholder. For instance, use `topydo ls - F "%z %r" to show a color in front of an item. Items with a red block are overdue. See https://topydo.org/#FormatStrings for more info on these strings, and https://topydo.org/#ProgressColors for info on the exact meaning of the colors.

* The column mode shows these colors right away. Launch with `topydo columns`.

This is supported with version 0.10 which I released yesterday. Does it address your issue?

**Comment by inducer** [comment]
This is awesome. Thanks for all your work on topydo!
