### ISSUE TITLE
Case insensitive search (possibly as a default)

### ISSUE THREAD

**Issue by frmz** [bram85/topydo#119]
I think search should be case insensitive by default adding an option to make it sensitive with a flag, also it would be nice to have the search term highlighted somehow.

**Comment by bram85** [comment]
> I think search should be case insensitive by default adding an option
> to make it sensitive with a flag, also it would be nice to have the
> search term highlighted somehow.

The case (insensitivity) is Vim-like: the search is case insensitive by 
default. A word is looked up in a case sensitive fashion when it 
contains at least one capital character.

```sh
# matches topydo, Topydo, ToPyDo,...
topydo ls topydo

# matches just Topydo
topydo ls Topydo

# matches just Topydo, and variants of runs, Runs, RunS, etc.
topydo ls Topydo runs
```

What is lacking is to perform a case sensitive match with only lowercase 
characters. In Vim this is enforced with a `\c` flag.

Does that make the current implementation sufficient for you?

**Comment by frmz** [comment]
Yes! Sorry didn't notice this, its even better than my proposal!
