### ISSUE TITLE
Column UI: Removing / commenting shortcut from configuration has no effect

### ISSUE THREAD

**Issue by bram85** [bram85/topydo#136]
After removing the `d` shortcut from the configuration, `d` still removes items. `d` only becomes a noop when it is configured with an empty value:

```ini
[column_keymap]
d = 
```

**Comment by mruwek** [comment]
I would say, that this is expected behavior because of defaults set in: [`topydo.lib.Config._Config.defaults`](https://github.com/bram85/topydo/blob/master/topydo/lib/Config.py#L125).

**Comment by bram85** [comment]
I gave it more thought and I think the current shortcut implementation is OK.
But, I think the `del` subcommand needs a confirmation mode, because I happen to accidentally delete items every now and then.
