### ISSUE TITLE
'became active' items are listed with their old ID

### ISSUE THREAD

**Issue by MinchinWeb** [bram85/topydo#139]
If you have items that depend on another, by default they are not shown, but when the dependency is completed, `topydo` will display a message that the item has now become available. However, the id shown (if you are using line numbers) is likely to change as the completed items are archived.

Since that was a mess to write, here's an example:

```
# add the first item
> topydo add first item +test
|484| 2016-08-22 first item +test

# add the second item
> topydo add second item +test
|485| 2016-08-22 second item +test

# make the second item depend on the first
> topydo dep add 484 before 485

# list items; only the first shows
> topydo test
[...]
484   first item +test                                                  (today)

# do the first item
> topydo do 484
Completed: x 2016-08-22 2016-08-22 first item +test p:1
The following todo item(s) became active:
|485| 2016-08-22 second item +test id:1

# above, the second item was shown as being 485. However,
# by the time we can do anything, the item has actually moved
# to being at 484
> topydo test
[...]
484   second item +test                                                 (today)
```

I would expect that the 'item has become active' text should display the item number where it can be accessed for the next command, so after achieving has been accounted for.

**Comment by bram85** [comment]
Yes, I know what you mean and it also stings me a bit, the bug also occurs when using text-based identifiers (a printed ID "aab" becomes "aaa" in reality).

Not sure how to fix that though, archiving takes place after the subcommand has done its job. Perhaps a subcommand should have some post-archiving hook such that it can print correct IDs.

**Comment by MinchinWeb** [comment]
Would it be that simple to just run the 'list active' part of the command after the 'archive' command?

**Comment by bram85** [comment]
Yes, I'd think so. But I think it should be made more generic that any command can do something after archiving. Besides, we should be careful that those actions are read only.
