### ISSUE TITLE
Code refactoring for commands operating on multiple todo IDs

### ISSUE THREAD

**Issue by mruwek** [bram85/topydo#14]
As it was said under #8:
> Overall, the function has become a bit long and deeply nested (...)

I thought that it would be nice to have one common class for all commands dealing with multiple todo IDs (`do`, `del`, `pri`, `postpone` at the moment). I've implemented it here: https://github.com/mruwek/topydo/commits/multi-todos-cmds-refactoring (sorry about long branch name :P).

At this moment `MultiCommand` class has only two methods, but I believe in future we can put there even more reusable code (like some magic function for selecting all todos with given project or context). I didn't open new pull request yet, because I'm not sure if code is mature enough (naming convention etc.) and if You really perceive it as a step in the right direction. I'm open to any critique,

In near future `edit` and `depri` could also benefit from this,

**Comment by bram85** [comment]
Yes, I like this direction. Thanks for doing this, really appreciated and I'd be glad to pull this refactoring in when you think it's in good shape.

Please make sure it passes pylint, so it conforms to most the coding style. Moreover, in my code, I use the `p_` prefix for function arguments. In your new code that would only affect `get_todos`.

However, I think the `end` argument should not be in there, I would have passed in a list of (raw) todo IDs. When I read `get_todos(-1)` my first thought was: what does this argument mean? I think something like `get_todos(self.args)` is more readable.

For the rest, looking good.
