### ISSUE TITLE
Edit command does not work from columns

### ISSUE THREAD

**Issue by colinsullivan** [bram85/topydo#141]
Hello!

From columns view, when I press `e` to enter edit mode, edit the task, then save and quit the text editor, the task shows up at the bottom of the todo.txt unedited.

Also, I'm not sure why the edit feature creates a temporary file, couldn't the text editor just open up the todo.txt file directly (at the appropriate line number)?

**Comment by mruwek** [comment]
Hi,

> From columns view, when I press e to enter edit mode, edit the task, then save and quit the text editor, the task shows up at the bottom of the todo.txt unedited.

Which editor?

> Also, I'm not sure why the edit feature creates a temporary file

That was our design of choice allowing us to select multiple tasks for editing (try to use `topydo edit -e @work` or select tasks in columns mode with `m` key).

> couldn't the text editor just open up the todo.txt file directly (...)?

`topydo edit` without further input will do that :)

> (at the appropriate line number)

This is easy to achieve with vim or emacs, but not so easy with many other editors.

**Comment by colinsullivan** [comment]
Thanks for the background info. Editor is vim.

--------
Colin

**Comment by mruwek** [comment]
Can you also check:

>  does it work from column console and/or CLI mode (`topydo edit TODO_ID`).

After editing you use `:wq` to save and exit from vim or some other method? Does topydo show any output in column console (bottom part of screen) after returning from vim to topydo?

**Comment by colinsullivan** [comment]
Looks like the same thing happens in prompt mode:

```
topydo> ls
...
|575| 2016-09-29 @acontext the other task
|576| 2016-09-29 @acontext the task
...
topydo> edit 576
```
Now I edit with vim, adding another context at the end, then it prints the same task again (but puts it at the end of the todo.txt file):
```
|603| 2016-09-29 @acontext the task
```

Same exact behavior when using `topydo edit` from bash.

**Comment by mruwek** [comment]
- Which version of topydo do you have (`topydo -v`) - release or github's master?
- What is your OS and its version? (Linux - which distro, Windows, Windows + Cygwin, OSX, BSD - which distro,)?
- What version of Python do you have (`python -V`)?
- How do you end session in vim? `ZZ`, `:wq` or any other method?

**Comment by colinsullivan** [comment]
topydo 0.10.1
OS X 10.11.6
Python 3.5.1 installed with homebrew, topydo installed with pip3 after
that, however this is different than my default system python (Python
2.7.1).  I know topydo is using python3 because of the shebang at the top
of the topydo executable.
:wq

----------
Colin

**Comment by mruwek** [comment]
Can You install version from #143 and test it?

One of the many ways to install:

```
git clone https://github.com/bram85/topydo
cd topydo
git fetch origin pull/143/head:test-143
git checkout test-143
pip3 install . --user
```

(If `pip3` won't work try with `pip`)

**Comment by colinsullivan** [comment]
Confirmed!

This fixes the issue.

Tested on bash with `topydo edit`, from inside prompt, and `e` from columns
view.

----------
Colin

**Comment by bram85** [comment]
Merged in master.
