### ISSUE TITLE
Columns view does not refresh when todo.txt is changed

### ISSUE THREAD

**Issue by colinsullivan** [bram85/topydo#142]
If todo.txt is altered from outside, the columns view does not reflect the change.

**Comment by mruwek** [comment]
Not only columns, but also prompt mode. Implementing such idea is not a trivial one. I think we could however create some sort of "manual reload" functionality.

**Comment by bram85** [comment]
Prompt mode should detect a file change, do you mean it is broken now?

I'm aware that column mode lacks this detection.

**Comment by mruwek** [comment]
> Prompt mode should detect a file change, do you mean it is broken now?

Nope, I had some misconception about how it works in prompt mode. Everything is fine, just ignore my remark about prompt :)

**Comment by inducer** [comment]
It seems to me that the same protection afforded by prompt mode regarding file changes ("the file has changed, refusing to overwrite it") is not active in prompt mode. I feel like this has caused me to lose to-do items, which is *cough* bad. (I use owncloud sync to keep todo.txt synchronized across multiple devices, *and* sometimes I run multiple instances of topydo by accident.)

**Comment by p-phillips** [comment]
Are there any plans to add this detection to columns mode ?  I have found the column UI so useful that I have it up in a tmux pretty much all day.  I've noticed that if I forget to close it down and then open up somewhere else I can get conflicted copies of my todo.txt file.  I can fix these with vimdiff or get backups from Dropbox of course, but would be good if it had some sort of manual or auto reload.

**Comment by bram85** [comment]
It's pretty high on my list for next things to do, unfortunately time is a bit lacking at the moment.

[watchdog](https://github.com/gorakhargosh/watchdog) looks interesting to use, also for prompt mode.

**Comment by bram85** [comment]
I'm mostly done with the implementation of fixing this issue in prompt + column mode. There are still some issues pending (see commit message above), but in general it's working.

**Comment by bram85** [comment]
This is fixed in the `master` branch (but only tested on Cygwin).

**Comment by mruwek** [comment]
> This is fixed in the master branch (but only tested on Cygwin).

Working great here, also on Cygwin (tested vim editing and concurrent topydo instances). I've tested it on Linux but only functionality up to commit 4d31c14. I can test current master on Linux machine tomorrow.

Great work!

**Comment by tott** [comment]
Just want to document here that this also works great in Debian 10. One thing I noticed though is that it does not work on a symlinked file. I originally had a symlink pointing to my dropbox version of the todo.txt file - If i point topydo to this link instead to the dropbox origin the changes are not reflected. Pointing directly to the origin works flawlessly.
