### ISSUE TITLE
due date ranges

### ISSUE THREAD

**Issue by p-phillips** [bram85/topydo#146]
Hi.

Lovely CLI script.

Is there a way to pull out tasks with due dates in a range ?  For exampleL

`topydo ls due:-2w
`
to list any tasks with due dates in the next 2 weeks ?

Pete

**Comment by bram85** [comment]
Yes, like this: `topydo ls due:>=today due:<=2w`

**Comment by p-phillips** [comment]
Superb.    Thanks for getting back so quickly.

What about giving a range of dates ?  (between 2 weeks ago and today for example).

Is there somewhere where this is documented ?  I've spent quite a bit of time on the website and didn't pick up on the "<=" syntax.

Pete

**Comment by bram85** [comment]
The syntax is described on the page about [filter expressions](https://topydo.org/#FilterExpressions), in partical the section on filtering on date tags. It's a bit implicit, but you can pass multiple date filters to achieve the date range.

**Comment by p-phillips** [comment]
Ahh - I see - that's great.   Same syntax as you described in the first answer!  Sorry for being stupid.  So in summary, all filter expressions must match.  Thanks,. Pete
