### ISSUE TITLE
column view alternative configuration file

### ISSUE THREAD

**Issue by p-phillips** [bram85/topydo#147]
I find the columns interface very very useful and intuitive (great piece of work).

I'd like to have an alternative .topydo_columns config file which I could trigger with a command line flag in the same way as the main topydo config file (-x ~/.topydo_columns_dash2)

Had a quick look through the code and couldn't see anything obvious.

Is there code in there already to do this ?

**Comment by bram85** [comment]
No, at the moment you cannot load an alternative file as a commandline parameter, unfortunately.

So with the current version you'd need to work with the various locations where the configuration is looked up (as explained [here](https://topydo.org/#ColumnConfiguration)).

I think, when we implement this, that a column configuration file passed on the commandline should _override_ any other column definition on the standard lookup locations. The current behavior _adds_ columns of one file to the already processed column configuration files.

**Comment by mruwek** [comment]
>  The current behavior adds columns of one file to the already processed column configuration files.

I tend to disagree: https://github.com/bram85/topydo/commit/fb792426de3e35ccf15b4d875584039ff7d74e64

**Comment by bram85** [comment]
Ah, thanks, I thought we left the behavior as you initially implemented it.

**Comment by bram85** [comment]
Implemented in `master`, see commit 0175374.

**Comment by p-phillips** [comment]
Lovely. Just back from leave hence my tardiness in trying this out. I can confirm it works exactly as I'd hoped.
