### ISSUE TITLE
Combining columns with prompt mode?

### ISSUE THREAD

**Issue by cappallo** [bram85/topydo#154]
I haven't looked at the code that closely; how big of a job would it be to merge prompt mode with the prompt in columns view? Seems to me like it would be the best of both worlds...

**Comment by bram85** [comment]
That's quite some effort, because these two UIs are built with two different toolkits (prompt: prompt_toolkit, columns: urwid). The former UI provides out of the box support for completion, this needs to be reimplemented somehow in the column UI with urwid.

What exactly do you expect from a merged UI? Only to have completion available in the column mode, or is it more than that?

**Comment by mruwek** [comment]
Just for the reference, I've tried some time ago [`urwid.Terminal`](http://urwid.org/reference/widget.html#terminal), but without satisfying effect.

**Comment by slaecker** [comment]
Maybe as a workaround: Could you add some kind of 'auto refresh' to the columns so tasks added or removed to the todo.txt from outside topydo get taken into account? This way one could split the terminal via, for example, [tmux](https://tmux.github.io/) and have the columns in one pane and the prompt in another. Tasks could be added via prompt and would show up in columns. I have my terminal with topydo open all the time so I don't like exiting and reloading the columns to reflect changes coming from my android phone w/ Simpletasks via Syncthing.

**Comment by bram85** [comment]
@slaecker that was recently introduced in the `master` branch :)
Not yet released though, I hope to release it somewhere in the upcoming weeks.

**Comment by slaecker** [comment]
@bram85 That sounds great, keep up the good work, I love this tool.

**Comment by bram85** [comment]
FYI, topydo version 0.11 watches for external edits on the todo.txt file (install watchdog first through pip).

**Comment by mruwek** [comment]
Just for the reference: #168 provides support for completion inside Column UI. It's still work in progress code-wise, so use at your own risk.

**Comment by p-phillips** [comment]
Looking forward to auto-completion in column mode.   Is there an ETA ?

**Comment by bram85** [comment]
It's hard to give an ETA, but PR #168 is probably one of the last (major) things I'd like to merge before I proceed with publishing a new release. At the moment we're reviewing and revising it. Functionality-wise it is working quite nicely already.

**Comment by bram85** [comment]
The completion functionality in column mode was just merged (#168), thanks to @mruwek's work.
I consider this issue implemented.
