### ISSUE TITLE
relative dates for columns - weekends!

### ISSUE THREAD

**Issue by p-phillips** [bram85/topydo#155]
Evening all.

I'd like to have a column in columns mode with stuff for next weekend added:

```
[Weekend]                                                                       
title = Weekend                                                                 
filterexpr = due:saturday due:sunday @home                                  
sortexpr = desc:importance                                                      
show_all = 1          

```
Is it possible to pick out 'next saturday' and 'next sunday'  for example ?  

Pete

**Comment by bram85** [comment]
Sounds like the need for an OR expression, but that's (currently) not supported. Perhaps you could rewrite the filter to:

```ini
filterexpr = due:saturday due:sunday @home                              
```

**Comment by bram85** [comment]
```ini
filterexpr = due:>=sat due:<=sun @home
```

(Pressed submit too soon on mobile site)

**Comment by p-phillips** [comment]
Superb.  Thanks again guys.  I have moved totally from toodledo to
todo.txt/topydo - just wonderful.

Pete

2016-12-15 21:19 GMT+00:00 Bram Schoenmakers <notifications@github.com>:
