### ISSUE TITLE
focus colour in column mode

### ISSUE THREAD

**Issue by p-phillips** [bram85/topydo#156]
I'm trying to change the background colour in column mode so that it is a bit darker.  However it doesn't seem to matter what colour I use, the background color still stays that light gray colour

This is my ~/.topydo file:
```
[colorscheme]
priority_colors = A:light-cyan,B:light-yellow,C:light-blue,I:white,S:light-magenta,W:green,R:magenta
focus_background_color = blue  
```

Is there another config directive for column mode colours ?

Pete

**Comment by mruwek** [comment]
You're sure that you have version at least: d57d63e1bf97ea72bdeafa2c1f2450e5ff68b5dc

I've just tested current master with following config:

```
[colorscheme]
focus_background_color = 152                                                                                                                           
marked_background_color = light-blue
```

and it works flawless. 

![zrzut ekranu z 2016-12-23 16-51-16](https://cloud.githubusercontent.com/assets/500710/21457500/15f9c724-c930-11e6-9fe3-a3fe9f7921ab.png)

**Comment by bram85** [comment]
You could also check whether there's a configuration file in your working directory that overrides the setting in ~/.topydo.

**Comment by p-phillips** [comment]
Well the previous version was 0.10.1, but I did a:

`sudo pip3 install --upgrade https://github.com/bram85/topydo/tarball/master`

and the focus colour now works.

My version is still 0.10.1 though.  

Thanks.

**Comment by bram85** [comment]
Yeah, the version is yet to be bumped, just before I release the next version. I expect to release 0.11 next week.
