### ISSUE TITLE
Column mode issue

### ISSUE THREAD

**Issue by yfery** [bram85/topydo#157]
I installed topydo and everything work in CLI mode.

But when I want to use column mode,  nothing happened, and no error message. 

```
king@Aluminium ~  $ sudo pip3 install topydo[columns]
Requirement already satisfied (use --upgrade to upgrade): topydo[columns] in /usr/local/lib/python3.4/dist-packages
  Installing extra requirements: 'columns'
Cleaning up...
king@Aluminium ~  $ sudo pip3 install urwid
Requirement already satisfied (use --upgrade to upgrade): urwid in /usr/local/lib/python3.4/dist-packages
Cleaning up...
king@Aluminium ~  $ sudo pip3 install topydo
Requirement already satisfied (use --upgrade to upgrade): topydo in /usr/local/lib/python3.4/dist-packages
Cleaning up...
king@Aluminium ~  $ topydo columns
king@Aluminium ~  $ 
```

It seems that I have every dependencies needed. Did I miss something ?

**Comment by mruwek** [comment]
No idea.  What's your OS?

Try to install it locally with `pip3 install --user topydo` and `pip3 install --user topydo[columns]`

**Comment by bram85** [comment]
It's hard to diagnose, perhaps it's doing an implicit `topydo ls columns` (related to the default configured command). You can check by adding a todo item with 'columns' in your todo.txt file and see if it appears.

Do you have a configuration file, could you post it here, please? Perhaps it would give a clue what's going on.

**Comment by mruwek** [comment]
As Bram has said try:

`topydo add columns`
`topydo columns`

and show us the output and your configuration.

**Comment by yfery** [comment]
OS: raspbian 8.0

Bram is right: 
```
king@Aluminium ~  $ topydo add columns
|  9| 2017-01-16 columns
king@Aluminium ~  $ topydo columns
|  9| 2017-01-16 columns
```

I didn't create any configuration file for topydo. So I try to create one:
```
[topydo]
default_command = columns
```
Then launched command:
```
king@Aluminium ~  $ topydo -c .config/topydo/config
Synopsis: topydo [-a] [-c <config>] [-d <archive>] [-t <todo.txt>] subcommand [help|args]
          topydo -h
          topydo -v
...
king@Aluminium ~  $ topydo -c .config/topydo/config columns
Synopsis: topydo [-a] [-c <config>] [-d <archive>] [-t <todo.txt>] subcommand [help|args]
          topydo -h
          topydo -v
...
```

It seems that columns isn't known as a command

**Comment by mruwek** [comment]
Please provide also output of `topydo -v`

**Comment by yfery** [comment]
```
king@Aluminium ~  $ topydo -v
topydo 0.8

Copyright (C) 2014-2015 Bram Schoenmakers
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by bram85** [comment]
That explains a lot :)

column mode was only introduced in version 0.10. It looks like that `pip3 install topydo[columns]` did install the dependencies, but not topydo itself. So an upgrade would be appropriate:

```
pip3 install --upgrade topydo
```

(you should have 0.12 by then, released yesterday).

**Comment by yfery** [comment]
After some fights to remove what did, everything goes fine with those command:

```
sudo pip3 install --upgrade topydo
sudo pip3 install topydo[columns]
```

It seems that it was necessary to install with sudo mainly for dependencies.

Thanks for your help :) (and for topydo)
