### ISSUE TITLE
Path of config files

### ISSUE THREAD

**Issue by mimf** [bram85/topydo#159]
Hello,

According to https://www.topydo.org/, one can have the config file in  $HOME/.config/topydo/config. This is not working for me. The config file is not the problem, because if I copy it to  $HOME/.topydo it works just fine.

So, please tell me: Is $HOME/.config/topydo/config working for you?

**Comment by mruwek** [comment]
What's your OS? Also, please share the output of `topydo -v`.

Works for me on Cygwin and on Linux (Fedora 25).

**Comment by mimf** [comment]
```
~ topydo -v
topydo 0.8

Copyright (C) 2014-2015 Bram Schoenmakers
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```


I'm using Xubuntu 16.04
