### ISSUE TITLE
What does the "l" command do?

### ISSUE THREAD

**Issue by jucor** [bram85/topydo#165]
Dear all

I'm a bit confused: I just realised that doing "topydo l" shows fewer tasks than does "topydo ls". I also only now realise than "topydo l" is not even documented. The codebase is still too intricate for me to find out where it would be, so a pointer to understand what "topydo l" does would be very welcome.
Thanks :)

**Comment by jucor** [comment]
Ah! I understood! Boy that's tricky: because `l` is not a command, `Command.py:resolve_alias()` falls back on the default command (`ls` in my case), and passes all the arugments (`l` in my case) to that default command.
Therefore `topydo l`, instead of a shortcut to `ls`, ends up listing **all tasks that contain the letter l** -- hence hiding some tasks.
Wicked.

**Comment by bram85** [comment]
It's related to issue #116. There should be a message of some sort to
notify that items were hidden.

>

**Comment by jucor** [comment]
Makes sense. In my case, once I had noticed, the alias system was the perfect solution for my woes.
