### ISSUE TITLE
Change default editor for topydo

### ISSUE THREAD

**Issue by mimf** [bram85/topydo#170]
Hello, I've been using Topydo for a while and it's great. There's just one thing I'd like to change:

- Default editor;

Is it possible to change the default editor with which topydo edits tasks?

**Comment by bram85** [comment]
It's possible in the `master` branch, I implemented it a little while ago.
It will be released in the next version, but I cannot really tell when that
will be released.

Check the topydo.conf file in the master branch to configure the editor, or
use the -E flag in combination with the `edit` subcommand:

`topydo edit -E vim`

>

**Comment by bram85** [comment]
For reference, it was [merged](https://github.com/bram85/topydo/commit/edc11eeb28d949043cdd76f17963e4bd84fb2f23) a few days ago.
