### ISSUE TITLE
is boolean filter possible, and can you filter for no due date set

### ISSUE THREAD

**Issue by p-phillips** [bram85/topydo#179]
I'd like to be able to ignore items with context @home  where I have set a  due date more than 2 months away (so @home due:<2m) AND ALSO filter for items without a due date set.

I can't see a way to

1.  find dates with due date not set, and 
2.  do booleans - such as "@home (due:<2m | due:=null)

i.e., to match you require the @home context, and either a due date within the next 2 months or no due date set at all.

As always, because this topydo works so brilliantly it stimulates new and interesting questions about how to use it!

**Comment by mruwek** [comment]
@p-phillips wrote:
> I can't see a way to
> 1. find dates with due date not set, and
> 2. do booleans - such as "@home (due:<2m | due:=null)

For todos with `due` tag not set try: `topydo ls -- -due:`. It works by the way with any tag, so if you want to list todos with `foobar` tag not set try: `topydo ls -- -foobar:`.

As of today topydo supports only logical `AND` in filter expressions, and what You're asking is of course possibility to create expressions separated with some sort of `OR` operators. Right now it's not possible (cfr #177) and AFAIK nobody is working at the moment.

PS If You're not familiar with double-dash usage on the CLI, read [this](http://unix.stackexchange.com/questions/11376/what-does-double-dash-mean-also-known-as-bare-double-dash)

**Comment by p-phillips** [comment]
Cheers Jacek.  I was familiar with double dash  - but my usage is mainly column mode (I have a bunch of tmux sessions with multiple column config files running).

Good to know about the -due: option, but I **need** (!) logical `OR`  ;-)   Clearly not just me according to #177 but also clear that this is non-trivial.  

Thanks for the prompt reply anyway.  I'll keep my fingers crossed.

Pete

**Comment by bram85** [comment]
Let's track the issue via #177.
