### ISSUE TITLE
Obey ignore_weekends when adding a relative due date

### ISSUE THREAD

**Issue by jancp** [bram85/topydo#182]
Hello!

Today (a Thursday) I added a task like this: ```topydo add "(B) Do something due:3d"```

With a nice feature like ‘ignore weekends’ already implemented to calculate importance, I was surprised to find that the due date was set to Sunday. I would have expected Topydo would ignore the weekend here as well and set the due date to Tuesday.

Cheers!

Jan

**Comment by bram85** [comment]
You could use the 'b' suffix instead of 'd' to work with business days,
that would ignore Saturdays and Sundays.

So to achieve the same effect, you should use 'due:3b'.

I think that would address your concern.

Op do 8 jun. 2017 10:19 schreef Jan <notifications@github.com>:

**Comment by jancp** [comment]
I was unaware of that. Bedankt!
