### ISSUE TITLE
Additional output format for linenumber and text identifiers

### ISSUE THREAD

**Issue by rcraggs** [bram85/topydo#184]
Currently `%I` in the output format will print the todo's identifier in whatever format is given for the `identifiers` config item. 

I would like to see additional output format options that always output the numeric or text version of the identifier regardless of what is specified for `identifiers`. So for example (if %u is the text identifier and %n is the number identifier) if the `identifiers=linenumber` and the output format is given as `|%I| %s [%n %u]` then the output of an **ls** might be:

```
|1| task 1 [1 2o0]
|2| task 2 [2  jz]
```

if we change the identifier to text then the same command would give

```
|2o0| task 1 [1 2o0]
| jz| task 2 [2  jz]
```

**Why would this be useful**

IMO line numbers are the prettier and more concise way to identify todos and so it makes sense for that to be the default. However there are occasions when it's helpful to be able to get a semi-stable identifier for a task. For example I'd like to write a script that lets me attach notes to a todo using a command such as 

`todonotes task 1` (or some other expression that identifies a task 

that would open a file associated with that task.  A simple implementation would be to create a file with the same name as the task's "text" identifier using something like

```shell
#!/bin/bash

$EDITOR $(topydo ls -F %u $@)
```
to this this I'd need to be able to force the output format to give me the text identifier without needing to change it in the config file.

**Comment by bram85** [comment]
Thanks, good suggestion. It shouldn't be too hard to implement.

>
