### ISSUE TITLE
Column mode fails to install and error message refers to an earlier version of topydo

### ISSUE THREAD

**Issue by RonCam** [bram85/topydo#191]
Any help on interpreting why column mode is failing to install -- will be appreciated:
```
sudo pip install topydo[columns]
Downloading/unpacking topydo[columns]
  Downloading topydo-0.8-py2.py3-none-any.whl (92kB): 92kB downloaded
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1266, in prepare_files
    req_to_install.extras):
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2299, in requires
    "%s has no such extra feature %r" % (self, ext)
UnknownExtra: topydo 0.8 has no such extra feature 'columns'

Storing debug log for failure in /home/ron/.pip/pip.log
```
The _Traceback_ section has references to python2.7 so, thinking that may mean this installation is corrupt, I reinstalled the same version of python using synaptic.  To be exact, the version (both before and after) is 2.7.6.

Reinstalling python had no effect.  Installation failure error message remains the same, as before.  

As well, the installed topydo version is _not_ v0.8, as is being shown in the _UnknownExtra_ line:
```
ron@ron-gnulinux:~ > topydo -v
**topydo **0.12****

Copyright (C) 2014-2016 Bram Schoenmakers
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
As far as I'm aware, columns should be available in v0.12?

Also this in terminal is not producing the expected result:
```
pip3 install 'topydo[columns]'
Requirement already satisfied (use --upgrade to upgrade): topydo[columns] in /usr/local/lib/python3.4/dist-packages
  Installing extra requirements: 'columns'
Cleaning up...
ron@ron-gnulinux:~ > topydo columns
Some additional dependencies for column mode were not installed, please install with 'pip install topydo[columns]'

```
System information:
Linux Mint 17.3
All python versions present on system, for help in troubleshooting:
```
for p in $(compgen -c python); do printf "%-16s" $p; $p --version; done
python2            Python 2.7.6
python3.4m      Python 3.4.3
python3.4         Python 3.4.3
python3.4-configUsage: /usr/bin/python3.4-config --prefix|--exec-prefix|--includes|--libs|--cflags|--ldflags|--extension-suffix|--help|--abiflags|--configdir
python3.4m-configUsage: /usr/bin/python3.4m-config --prefix|--exec-prefix|--includes|--libs|--cflags|--ldflags|--extension-suffix|--help|--abiflags|--configdir
python3-config  Usage: /usr/bin/python3-config --prefix|--exec-prefix|--includes|--libs|--cflags|--ldflags|--extension-suffix|--help|--abiflags|--configdir
python3          Python 3.4.3
python2.7       Python 2.7.6
python3m-config Usage: /usr/bin/python3m-config --prefix|--exec-prefix|--includes|--libs|--cflags|--ldflags|--extension-suffix|--help|--abiflags|--configdir
python             Python 2.7.6
python3m        Python 3.4.3
```

**Comment by RonCam** [comment]
I (thought I) saw an _urwid_ entry while browsing the _topydo_ directories, so thought this dependency had been satisfied.

However, I just 'fired up' synaptic, searched for 'urwid' and found _five_ packages with this term in their descriptions -- and none of them are installed.  I see nothing that's named (just) _urwid_, however.  

I am now trying to find the full name of the 'urwid' package that's needed, so I may select the correct one. 

Any help will be appreciated!

**Comment by mruwek** [comment]
1. `pip uninstall topydo`
2. `pip3 uninstall topydo`
3. `pip3 install topydo[columns] --upgrade --user` - add quotes if you use ZSH.

For newest and greatest released version of topydo use **always** and **only** `pip3`. `--user` is encouraged by me, so you don't have to type root password every time you want to update anything.

If you're crazy enough for development version:

1. `git clone https://github.com/bram85/topydo`
2. `cd topydo`
3. `pip3 install .[columns] --user --upgrade`

**Comment by RonCam** [comment]
Wow, that's great! Thanks for the rapid reply -- I was anxious to see how the Columns worked.
I am a complete noob about the difference between pip, pip2 and pip3, and what each one does.  Zero previous experience here, in installing python programs.  

Then in this case, changing the pip version also changes the version of the program being installed.

Only one thing a bit strange:  with the other installation (of the wrong version, so it seems) _topydo_ ran as soon as I opened terminal, (which gives a prompt at $HOME on my system) and then typed _topydo ls_  (and _topydo_ -- etc, etc.).

With this installation I had to open the directory -- 
_~/.local/bin >_ 
and then type _./topydo ls_ -- and _./topydo columns_ (etc.,etc.) .

Apparently I will have to fix the path to get it to work, directly, from any other location, as it did the first time.

Is this normal behavior for topydo's _pip3_ installation, or did something go slightly wrong?  If it's the second, something went slightly wrong, could it be affecting anything else, adversely?

Just trying to make sure I now have a 'solid' installation, and then I'll move on to learning the program.

**Comment by bram85** [comment]
Most likely, your `$PATH` variable first lists /usr/bin, then /usr/local/bin and then (if at all), ~/.local/bin/.

Note that `pip2` and `pip3` serve two cohabitated Python versions on your system, each with their own installation directories (/usr/lib/pythonX.Y/site_packages, or likewise, ~/.local/lib/pythonX.Y/site_packages when you use pip's `--user` flag. I would recommend using `--user`, not only to omit password prompts, but also to make sure that your pip installs won't interfere with your distribution's Python packages.

Typically, `pip` is an alias for `python2` for backward compatibility reasons. In the context of topydo, you should always use `pip3` because topydo is Python 3 only. You mentioned topydo 0.8 somewhere in your first post, that was the last Python 2.7 version I released of topydo. I suspect that you used the old pip to install topydo or some of its dependencies at some point.

**Comment by mruwek** [comment]
@RonCam:
> Just trying to make sure I now have a 'solid' installation, and then I'll move on to learning the program.

Yes, You do. All You have to do now is fix your `$PATH` in your shell configuration. Just add something like:
`PATH=$PATH:~/.local/bin` to your `.bash_profile` (or `.bashrc` if you want to set such `$PATH` only for interactive shells) if you use Bash - `.zprofile` or `.zshrc` accordingly if you use ZSH.

**Comment by RonCam** [comment]
@bram85; @mruwek:
Thanks to both for the informative replies -- all is now clear, and I have learned why I was having problems.
 
Now, I am having a problem installing a different component of _topydo_, but to help other users find that thread, that help request will go under a separate Subject heading.

**Comment by mruwek** [comment]
@RonCam:
> do this in terminal:
> `sudo kate /etc/environment`
> and the PATH string appears for editing and saving. It works after a logout - login.
> 

Erm. In most cases this is not the way you should do that. It is usually good practice to not  set user-specific settings in a file that is system-wide. Set your `$PATH` rather in aforementioned `.bashrc` or `.bash_profile` (or `.zshrc` or `.zprofile`) and add a keyword `export` to propagate it also to subshells:

Here is for example the default content of `.bash_profile` for Fedora, but it should work for BASH in any distro:

```
PATH=$PATH:$HOME/.local/bin:$HOME/bin

export PATH
```
