### ISSUE TITLE
Using ls and expression-filters with :created tag seems not to work

### ISSUE THREAD

**Issue by RonCam** [bram85/topydo#199]
I am attempting to familiarize myself with the use of filters by reviewing past advice given to others, duplicating the example, and then modifying it and observing if it still works (or doesn't work, in this case). 

For example, this works, taken from 'due date ranges #146':
topydo ls due:>=today due:<=2w

I would like to modify this, to display all tasks created within the past two weeks, and thought this should do it:
ls created:<=today created:>=2w
However, it just gets the topydo prompt back again, with no tasks listed.

Do I have a syntax error, or do logical expressions not work with the 'created:' tags?  Am I using the terminology correctly -- _<=today_ qualifies as a valid logical expression?
Any help will be appreciated!

**Comment by bram85** [comment]
You're almost there, the expression should be:

```
ls created:<=today created:>=-2w
```

Mind the minus sign. `-2w` substitutes to a date in the past, while `2w` is substituted with a date in the future. With a future date, no task would match, yielding an empty result.

**Comment by RonCam** [comment]
Many thanks for an excellent program, and the rapid reply!  Yes, now that you've explained it, it's logical and makes sense.
