### ISSUE TITLE
Provide "edit" command

### ISSUE THREAD

**Issue by mruwek** [bram85/topydo#2]
It would be nice to have possibility to edit todo.txt in $EDITOR. I can imagine 3 ways of using this command:

1. `todo edit` - open todo.txt in $EDITOR
2. `todo edit archive` - open done.txt
3. `todo edit <NUMBER>` - open todo.txt and go to specified task/line

Bottom line: inspired by work of Dave Hein @dhein
http://github.com/dhein/todo.txt-cli/blob/pub-addons-new_export2/edit

**Comment by bram85** [comment]
Didn't know that extension by Dave Hein, but I was actually already working on this.
In a local branch that, I didn't push yet, I already have an 'edit' subcommand that implements item 1 in your list.

I had a different implementation of "edit <NUMBER>" in mind, being to open a temporary file with that specified todo item. You could be able to specify more numbers, or maybe even a +Project to edit all items in that project. That last item is not implemented yet.

Regarding item 2, I'd say to use a flag (-d) instead a full word. "archive" could also be a regular expression that matches items with the word archive in it.

**Comment by mruwek** [comment]
> I was actually already working on this.

Great :) I'm waiting then for the update.

> You could be able to specify more numbers, or maybe even a +Project to edit all items in that project.

That would be very useful. Any ETA on this?

> Regarding item 2, I'd say to use a flag (-d) instead a full word.

Agreed.

**Comment by bram85** [comment]
> > You could be able to specify more numbers, or maybe even a +Project to edit all items in that project.

> That would be very useful. Any ETA on this?

ETA is difficult to tell. I could deliver functionality 1) very soon to master because that's basically ready. I just waited because I assumed to be the only user :)

At the moment I'm a bit busy with other things, but item 3) is something I miss myself in my day-to-day work so probably I'll scratch that itch somewhere this month or next month.

**Comment by kidpixo** [comment]
+1 on this!

**Comment by mruwek** [comment]
I really believe that code above is not ready for merge, but hey, it works!

Waiting for insights, comments and patches :)

>  or maybe even a +Project to edit all items in that project

For that to happen we need to implement it in `TodoListBase.todo` function. `pri`, `postpone`, `do`, `del` would also benefit from such extension.

**Comment by bram85** [comment]
I'll leave this issue open since the `archive` option is not implemented (use case 2 in your original report). It's up to you what to do: close this issue, now the `edit` subcommand is merged, or leave it open in case you'd like to implement the archive case.

**Comment by mruwek** [comment]
Closing as it is fully implemented now and merge in master.
