### ISSUE TITLE
Difficulty in getting topydo columns to read custom column definition file

### ISSUE THREAD

**Issue by RonCam** [bram85/topydo#203]
I'm using the example column definitions, from the documentation, pasted into a file and saved in the working directory.

Probably it's something obvious, because this does cause the three-column example to override the single-column default:
`~$ topydo columns -l /home/ron/Sync/TodoTxt-netbook/topydo_columns.conf`

However, topydo _reverts to the default column configuration,_ when using this command:
`~$ topydo columns`

I have set-up the topydo working directory as follows, in the config file:
```
[topydo]
filename = /home/ron/Sync/TodoTxt-netbook/todo.txt
archive_filename = /home/ron/Sync/TodoTxt-netbook/done.txt
```

I thought it was a PATH problem, so my path was modified to include the topydo working directory, as follows:
`/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/ron/.scripts:/home/ron/.local/bin:/home/ron/Sync/TodoTxt-netbook`

All the above has been select-copy-pasted to prevent typographical errors.  I saw in the Issues section that a similar problem arose when using an old version, so is this OK?
```
~$ topydo -v
topydo 0.13
```
Can anyone see my problem?

**Comment by bram85** [comment]
Are you in the directory /home/ron/Sync/TodoTxt-netbook/ when you invoke `topydo columns`, because it would lookup the .conf file in the current working directory. If you need the column definition from any directory, you should install it in a more global location such as your home directory, as documented on the page below. PATH has no effect, though.

https://topydo.org/#ColumnConfiguration

**Comment by RonCam** [comment]
Thanks very much for the explanation.  I was _mis_understanding the term 'working directory' to mean the location of _todo.txt_ and _done.txt_, after that location had been defined in the (general) _topydo config_ file.  I now see that wasn't sufficient, because I wasn't in the Sync directory, when the command _topydo columns_ was invoked.

I will put it in one of the 'more global' locations as you suggested and I'm sure everything then will 'work as advertised'.  In the unlikely case that the problem persists, I'll reopen this thread.

I'm renaming the Subject line to be more descriptive of the problem and its solution, for the benefit of other users who may have the same misunderstanding.  Please let me know if the way I've summarized it could be improved.
