### ISSUE TITLE
Best way to recover archived tasks, that can no longer be 'reverted'?

### ISSUE THREAD

**Issue by RonCam** [bram85/topydo#204]
Not really a problem-type Issue, but I am trying to understand _topydo_'s capabilities and posed to myself the question of how to re-activate a task already archived in _done.txt_, but no longer in the _revert_ buffer.  

I came across this answer to another user's closed _Issue_, who only wanted to view -- not reactivate -- items in _done.txt_, and thought it could be the first step toward an answer for what I was attempting:
> You could run topydo -t done.txt ls -x. What it does is to treat the done.txt file as your todo list, and with -x you show all items (by default, completed items are hidden).

I tried the above, displayed the done items and attempted to select-copy in terminal, then paste (still in terminal) after typing add, but the paste buffer seemed empty (for some reason?), and so the operation failed.

I next tried with _edit -d,_ which (also) displayed the entire _done.txt_ file, this time inside the text editor (instead of in terminal), did select-copy, opened a second instance of terminal, and then successfully did a paste, after entering an add command.

**Question:**
Is this the best, or only, way of reactivating 'done' tasks?  
This assumes the task is no longer in the revert buffer.  

However, this second method _also_ fails to accomplish the paste, _if_ the text editor is closed first, in order to regain a prompt.  It pastes properly only if a second instance of terminal is opened, before closing the editor.

This is not bad and gets the job done, but the way it works makes me wonder if I'm devising a 'hack' to work around a problem of my own making?  I can't find a more direct way, in the documentation.  Did I miss it?

**Comment by bram85** [comment]
Moving items back and forth between todo.txt and done.txt is not well supported by topydo, especially in the reverse direction of moving an item back into todo.txt.

So for now, the way to proceed is to open todo.txt and done.txt in a text editor and move the lines manually.

I can't explain why copypaste doesn't work, it's not really in topydo's domain, but an issue with your OS. I know in some environments (especially on Linux), there is a difference between the clipboard and a selection buffer. And some clipboard tools allow you to sync these two 'clipboards'. But again, that's a bit out of my expertise these days (also without knowing in which environment you're working).

**Comment by RonCam** [comment]
Thanks for the feedback.  
The OS is a slightly-old version of Bodhi Linux, with Enlightenment 17.  From what you said, I may expect it to work differently on my desktop system, running Linux Mint 17.3 KDE.  And it may change yet again, when I upgrade to Mint18, and its updated version of KDE.  

Thanks for letting me know there's no 'special way' that experienced users know about, and so, whatever works for a particular desktop environment -- will be fine.

I was mainly thinking about how to best reuse a task's known-good filter without retyping it and possibly introducing typographical errors. 

Thanks again for a great program!
