### ISSUE TITLE
Filter to selectively list Tasks without any Context, and/or without any Project?

### ISSUE THREAD

**Issue by RonCam** [bram85/topydo#205]
I see examples of filters to operate with Tags in this way, but not with the '@' and '+' parameters.
The idea is for _ls_ to bring up only Tasks that do not contain a Context or a Project -- of _any_ type.
It could be useful, to alert the user if some Tasks are in need of an edit, when this omission was accidental.
Is this possible?  Or, is there another way of doing the same thing?

**Comment by bram85** [comment]
You could use the `-+` or `-@` as a filter expression to list all items without a plus or @ sign. It's not waterproof though, when you have one of these characters used for different purposes (e.g. you mention an email address in your todo item).

Personally, I use `-+` all the time and it works quite well.

**Comment by RonCam** [comment]
Thanks again, that's exactly what I wanted to do.  The capabilities of _topydo_ are amazing! 

I'm certain it will work as well for me, as it does for you.  Any problems, and I'll re-open the thread.
