### ISSUE TITLE
Is the 'Y' keyboard shortcut for Columns working for everyone else, or is it just me?

### ISSUE THREAD

**Issue by RonCam** [bram85/topydo#206]
I tried to use the 'Y' shortcut in Columns mode, and what happened seems identical to using the 'E' shortcut -- in other words, a box opened below the columns, with options to _edit_ the column definition.

I can see no difference whether or not a Task, or Tasks, are Marked/Selected.  I tried with both left and right Shift keys, to produce a capital-Y, but the result is the same.

From the documentation I gather this shortcut should be for 'Saving' the column, but I don't see anything on the screen to indicate something has been 'Saved'.

Could I be accidentally overriding the default shortcut?

Any advice on what I'm doing wrong would be most appreciated.

---
$ td --version
topydo 0.13
Copyright (C) 2014-2017 Bram Schoenmakers

**Comment by bram85** [comment]
`Y` stands for `yank`, from the world of Vi. It allows you to copy a column - while making (small) adjustments along the way.

Saving columns is not supported, I wonder in what part of the documentation you read that.

**Comment by RonCam** [comment]
@bram85 Yes, of course, you are correct.  The documentation says 'Copy'.  Thanks for the hint about Vi.  I think I'll understand the purpose and utility of the Y command, after checking Vi's documentation.
