### ISSUE TITLE
ls -N doesn't calculate screen size correctly

### ISSUE THREAD

**Issue by karbassi** [bram85/topydo#208]
See gif
![2017-11-06 20 17 37](https://user-images.githubusercontent.com/17738/32474038-1e86b53c-c330-11e7-96c4-65baf05cc0b7.gif)

**Comment by mruwek** [comment]
Well, I believe it does calculate screen correctly, but You have more than one line of shell prompt. I'm sure topydo is not aware of multiline prompts.

**Comment by karbassi** [comment]
@mruwek I fully accept that. 🤓 

@bram85 here's my thoughts.

After looking into it, `_N_lines()` in `commands/ListCommand.py` doesn't work with my shell (zsh).

https://github.com/bram85/topydo/blob/0b33791ac7cf3f9c60a3d800dfa5ef3476188c16/topydo/commands/ListCommand.py#L168-L196

For example: 

```python
import os
print os.getenv('PROMPT', '')
```

outputs nothing for me.

Here's a quick way to get the PS1 for zsh at least. I think it would work for all shells (`bash`, `fish`, etc)

```python
import os
import re
import subprocess

shell = os.environ['SHELL']

if "zsh" in shell:
    PS1 = subprocess.check_output([shell,'-i','-c','echo $PS1'])
    a = re.findall('\\n', PS1)
    print len(a)
```

**Comment by bram85** [comment]
Hmm, but the number of lines in your prompt should be recorded in the `else` clause of the code snippet you posted (lines 189 and 190). It should be executed in your case as you're not running Windows.

So I wonder what's causing topydo's code to fail and yours to succeed.

**Comment by karbassi** [comment]
@bram85 The line `os.getenv('PS1', '')` returns the empty string because PS1 isn't set as an env variable within python for some reason.

![2017-11-10 11 28 55](https://user-images.githubusercontent.com/17738/32670778-6b8d2b04-c60a-11e7-8cce-7d8b05f5ded8.gif)

**Comment by bram85** [comment]
Strange, I don't see this behavior. But I checked with Python 3.6, I see in your screencast that you checked with Python 2.7. Can you reproduce it with Python 3?

**Comment by karbassi** [comment]
@bram85 Same issue with Python 3 (3.6.3)

![2017-11-11 11 09 47](https://user-images.githubusercontent.com/17738/32691679-f4b7055a-c6d0-11e7-931c-3c07827a63db.gif)

**Comment by mruwek** [comment]
@karbassi 
Can You give us output (text) of the `os.environ`?

**Comment by bram85** [comment]
Is the python executable a wrapper script, possibly executing python in a subshell, or resetting PS1 otherwise?

**Comment by karbassi** [comment]
@bram85 no. None of that.

@mruwek see below
<details>
 <summary>`os.environ` with private data removed</summary>

```json
{
"ADB_VENDOR_KEYS": "/Users/REMOVED/.local/share/android/.android",
"ANDROID_SDK_HOME": "/Users/REMOVED/.local/share/android",
"AWS_CONFIG_FILE": "/Users/REMOVED/.config/aws/config",
"CARGO_HOME": "/Users/REMOVED/.config/cargo",
"COLORFGBG": "7;0",
"COLORTERM": "truecolor",
"COMMAND_MODE": "unix2003",
"COMPOSER_CACHE_DIR": "/Users/REMOVED/.cache/composer",
"COMPOSER_HOME": "/Users/REMOVED/.local/share/composer",
"EDITOR": "/usr/local/bin/vim",
"GEM_HOME": "/Users/REMOVED/.local/lib/gems",
"GEM_PATH": "/Users/REMOVED/.local/bin",
"GEM_SPEC_CACHE": "/Users/REMOVED/.cache/gem",
"GIT_SSH_COMMAND": "ssh -F /Users/REMOVED/.config/ssh/config  2>/dev/null",
"GNUPGHOME": "/Users/REMOVED/.config/gnupg",
"GRADLE_USER_HOME": "/Users/REMOVED/.cache/gradle",
"GTK2_RC_FILES": "/Users/REMOVED/.config/gtk-2.0/gtkrc",
"HISTFILE": "/Users/REMOVED/.config/zsh/.zsh_history",
"HOME": "/Users/REMOVED",
"HOMERC": "/Users/REMOVED/.config/htop/htoprc",
"HTTPIE_CONFIG_DIR": "/Users/REMOVED/.config/httpie/",
"INPUTRC": "/Users/REMOVED/.config/readline/inputrc",
"IPYTHONDIR": "/Users/REMOVED/.config/ipython",
"ITERM_PROFILE": "REMOVED",
"ITERM_SESSION_ID": "REMOVED",
"KDEDIR": "/Users/REMOVED/.config/kde",
"KDEHOME": "/Users/REMOVED/.config/kde",
"LANG": "en_US.UTF-8",
"LC_CTYPE": "en_US.UTF-8",
"LESS": "-R",
"LESSHISTFILE": "/Users/REMOVED/.local/share/less/history",
"LOGNAME": "REMOVED",
"LSCOLORS": "Gxfxcxdxbxegedabagacad",
"MANPATH": "/usr/local/opt/coreutils/share/man:/usr/local/man",
"MYSQL_HISTFILE": "/Users/REMOVED/.local/share/mysql/history",
"OLDPWD": "REMOVED",
"PAGER": "less",
"PASSWORD_STORE_DIR": "/Users/REMOVED/.local/share/password-store",
"PATH": "/Users/REMOVED/.rbenv/shims:/usr/local/opt/coreutils/libexec/gnubin:/usr/local/opt/ruby/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin",
"PENTADACTYL_INIT": ":source /Users/REMOVED/.config/pentadactyl/pentadactylrc",
"PIP_CONFIG_FILE": "/Users/REMOVED/.config/pip/pip.conf",
"PIP_LOG_FILE": "/Users/REMOVED/.local/share/pip/log",
"PSQLRC": "/Users/REMOVED/.config/psql/psqlrc",
"PSQL_HISTORY": "/Users/REMOVED/.local/share/psql/history",
"PWD": "REMOVED",
"PYLINTHOME": "/Users/REMOVED/.local/share/pylint",
"PYLINTRC": "/Users/REMOVED/.config/pylint/pylintrc",
"PYTHONSTARTUP": "/Users/REMOVED/.config/python/pythonrc",
"RBENV_SHELL": "zsh",
"RUSTUP_HOME": "/Users/REMOVED/.config/cargo",
"RXVT_SOCKET": "/urxvtd.sock",
"SECURITYSESSIONID": "REMOVED",
"SHELL": "/bin/zsh",
"SHLVL": "2",
"SSH_AUTH_SOCK": "/private/tmp/com.apple.launchd.BnTEeH1xuR/Listeners",
"TERM": "screen-256color",
"TERMINFO": "/Users/REMOVED/.config/terminfo",
"TERM_PROGRAM": "iTerm.app",
"TERM_PROGRAM_VERSION": "3.1.5",
"TMPDIR": "REMOVED",
"TMUX": "/private/tmp/tmux-501/default,885,0",
"TMUX_PANE": "%33",
"UPDATE_ZSH_DAYS": "30",
"USER": "REMOVED",
"VAGRANT_DOTFILE_PATH": "/Users/REMOVED/.local/share/vagrant",
"VAGRANT_HOME": "/Users/REMOVED/.local/share/vagrant",
"VIMINIT": "source /Users/REMOVED/.config/vim/vimrc",
"VIMPERATOR_INIT": ":source /Users/REMOVED/.config/vimperator/vimperatorrc",
"VIMPERATOR_RUNTIME": "/Users/REMOVED/.config/vimperator",
"XAUTHORITY": "/Xauthority",
"XDG_BIN_HOME": "/Users/REMOVED/.local/bin",
"XDG_CACHE_HOME": "/Users/REMOVED/.cache",
"XDG_CONFIG_HOME": "/Users/REMOVED/.config",
"XDG_DATA_HOME": "/Users/REMOVED/.local/share",
"XDG_LIB_HOME": "/Users/REMOVED/.local/lib",
"XPC_FLAGS": "0x0",
"XPC_SERVICE_NAME": "0",
"ZDOTDIR": "/Users/REMOVED/.config/zsh",
"ZSH": "/Users/REMOVED/.config/oh-my-zsh",
"_": "/usr/local/bin/python3",
"__CF_USER_TEXT_ENCODING": "0x1F5:0x0:0x0",
"__PYVENV_LAUNCHER__": "/usr/local/bin/python3",
"npm_config_userconfig": "/Users/REMOVED/.config/npm/npmrc"
}
```

</details>

**Comment by bram85** [comment]
And is PS1 exported?

**Comment by karbassi** [comment]
@bram85 no, it's not.

**Comment by karbassi** [comment]
@bram85, neither PS1 or PROMPT are in my `os.environ`. My `zsh` config uses `PROMPT` rather than `PS1`.

When I do `os.environ.get('PS1')` or `os.environ.get('PROMPT')`, I get nothing. But in my shell, if I `echo $PS1` or `echo $PROMPT`, both output my command prompt.

Do you think it has to do with zsh or [oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh)

**Comment by bram85** [comment]
The question is how PS1 is set (topydo doesn't consider PROMPT). Is it done with `export`? Because only then the variables are propagated to child processes.

Could you post the relevant shell configuration here? Or try `export PS1=$PS1` in your .zshrc and see if that helps.

**Comment by bram85** [comment]
A kind reminder for the questions in my last post. Because having `export` or not is basically the only lead we have for the behavior you described.

**Comment by karbassi** [comment]
👍
