### ISSUE TITLE
Time-stamps (HH:MM) in Tasks, in v0.13, are interpreted as 'tags' and their use should be avoided (pending next update)

### ISSUE THREAD

**Issue by RonCam** [bram85/topydo#211]
I am trying to become accustomed to the operation of _topydo_, but am confused by the way this Task was changed, after entry:

Original Task, as copied from one line of todo.txt file (and, this is the way it was originally entered, except for the start date, which was applied automatically):

> 2017-11-22 "MM (Pilates) 12 noon, leave 11:30" due:Friday +rec:1w

Same task, as copied from terminal:
```
topydo> ls Pilates
|44| 2017-11-22 "MM (Pilates)12 noon, leave +rec:1w 11:30"
```
The due: tag is missing, and as a result, the Task fails to show in the Column that has its filter is set to select for this tag.

Also: is there any way of including a time notation (hours:minutes am/pm) in a Task, so that it will not be removed and shifted to the end of the line -- as in the example copied from terminal?  Or, is this intentional behavior, and if so, what is its purpose?

Note, I tried to protect the Task with quotes, but these were removed and replaced to cover the entire line.  Am I using quote marks correctly, and is this their intended purpose?

----------------------
~$ topydo -v
topydo 0.13

**Comment by bram85** [comment]
Can you post the [ls] section in your configuration here? Perhaps you're missing a placeholder for the due date in the list_format entry.

As for 11:30, it is considered a tag (name 11, value 30). Perhaps that's not so practical, and it shouldn't be like that when it's all numbers.

**Comment by RonCam** [comment]
Thanks for helping me to find out what is happening!
I can't locate a [ls] section in the _config_ file, so I'll post what I do find there, and perhaps you'll see something?
```
[topydo]
filename = /home/ron/Sync/TodoTxt-netbook/todo.txt
archive_filename = /home/ron/Sync/TodoTxt-netbook/done.txt
backup_count = 4
# [topydo] -- changed to Comment -- delete if still works, otherwise bring it back.
[colorscheme]
# focus_background_color = changed to darker-than-darkgray
focus_background_color = 239
# identifiers = text
identifiers = linenumber
[edit]
editor = leafpad
[aliases]
# Edit all memos
memo-edit = edit -x -e - -due:
# List active memos
memo-list = ls - -due:
# View all memos
memo-all = ls -x - -due:
```
Could it have been an interaction triggered by the adjacent time entry, when it was interpreted as a tag?
If there's a particular time of day associated with performing a Task, is there any way one could do this?

**Comment by bram85** [comment]
In the next topydo, tags with HH:MM format won't be considered a tag-value pair (see commit referenced above).

If your todo.txt contains the literal text `due:Friday`, then this is not recognized as a proper due date. This notation with relative dates only works when you feed it to `topydo add`, it will convert `Friday` in a proper date in YYYY-MM-DD format. So if you rewrite it in your todo.txt file, the due date will be shown.

**Comment by RonCam** [comment]
Thanks for looking after my problem and clarifying when a date abbreviation (or for that matter, a relative date?) may, or may not, be used.

You have also mentioned the proper date format, as required by topydo: YYYY-MM-DD.

I have found that when rapidly entering data from another source that shows a date as DD-MM-YYYY, I may occasionally enter it in that sequence and then, when it becomes obvious that the Task is misbehaving, I stare at it for a long time, wondering what could be the problem, since the date seems correct because it matches the source.

Would it be generally helpful, to have _topydo_ display a simple error message on the command line, when the user tries to enter a date the violates correct format rules?  Or, even better, also when displaying an erroneous date that may have been directly placed into the todo.txt file?  

I am thinking of something simple, such as, 'Error - wrong date format'.  Nothing more should be needed as the user will now know where to look, to make the correction.

**Comment by RonCam** [comment]
Temporary work-around for Tasks that need a time to be specified, for example, 12:30pm:
**12h30m** (12 hours, 30 minutes)
By avoiding the ':', this term is not interpreted as a Tag.

But, @bram85's idea to patch the code is better, because most users will not know to do this and so, will end up with unwanted tags and possible errors in parsing the remainder of the Task.

**Comment by RonCam** [comment]
Another work-around, more intuitive that first, because it (almost) retains the original time format:
12: 30
Note, a single space-character follows the colon.
Now the time is no longer interpreted as a Tag.
