### ISSUE TITLE
Problem with changes in show relevant items changes in 

### ISSUE THREAD

**Issue by RonCam** [bram85/topydo#212]
Could someone confirm whether this is working correctly?  I made a change to Show Only Relevant Todo Items in Columns mode, saved, then went to the relevant columns configuration file, and saw this:
show_all = 1
The file seems not to be tracking changes made after pressing E in a column.
I checked the file permissions on the config files (both) and opened them to 'Anyone' to eliminate a permissions problem.
Can this be duplicated, or is there a problem with my installation?

**Comment by bram85** [comment]
There's nothing wrong with your installation, the column definition files are read only (for now). Any changes to the columns should be made in the configuration file.

**Comment by RonCam** [comment]
Thanks very much for your rapid reply.  It gives a good explanation for what I saw happening.  

This is no problem, now that I know why the Tasks that appear, or do not appear, in Columns mode seemed to be behaving erratically -- if I understand your answer correctly, I can work around it, by making changes _only_ after opening the Columns config file in a text editor.  

I had mistakenly assumed that the 'Save' option in Columns mode was intended to modify the configuration.  

I shall 'neaten up' this post's Subject so others may learn from your answer, when searching the Issues section.
