### ISSUE TITLE
Is there any benefit from entering custom Tags into config file?

### ISSUE THREAD

**Issue by RonCam** [bram85/topydo#215]
I notice that pre-configured tags appear in the config file, in this format, according to the documentation:
For example,
```
[tags]
tag_star = star
```
If I want to use a custom tag that I've created for a special purpose, is there a benefit -- or, does it work any better -- if I put it into the config file, following the same pattern as with the star Tag?
For example, if I want to have a 'memo' Tag,
```
[tags]
tag_memo = memo
```
Then, I would use it as _memo:1_ in a Task.

I have it set-up this way right now, just because I wanted to follow the pattern in the documentation, but I am wondering exactly how this differs from simply using the tag, without making a config entry.

**Comment by bram85** [comment]
No, there's no need to declare your own tags in the configuration file, just use them :)

The reason to declare `star`, `due` and `t` in the configuration file is that they have a special meaning in topydo (`star` is used for calculating the importance value of an item).

**Comment by RonCam** [comment]
Thanks!  I now have a better understanding of how to use topydo.
