### ISSUE TITLE
tasks marked as complete externally are not recognised as done

### ISSUE THREAD

**Issue by mbroedl** [bram85/topydo#219]
(topydo 0.13)
Topydo does not recognise when I have marked a task as done ('x ' at the beginning of the line) but still displays them in all modes. When setting them as done in topydo, they then read:
`x 2018-02-10 x here is the task`

**Comment by bram85** [comment]
Did you have a completion date as well right after x? That is mandatory in the todo.txt format in order to be recognized as being done.

**Comment by bram85** [comment]
Did you have a completion date as well right after x? That is mandatory in the todo.txt format in order to be recognized as being done.

**Comment by bram85** [comment]
Oops, accidentally closed the issue. Please reopen when a date was actually present

**Comment by mbroedl** [comment]
Ah,thanks @bram85. Seems like I did not read the specs closely enough.
The image accompanying the description is very misleading:
[link](https://github.com/todotxt/todo.txt/blob/master/description.png)
I understood it as: x for completion, and if there is a completion date it must have a start date as well. Since I usually did not have start dates, I thought I couldn't use completion dates... :/

Many thanks! Sorry for being inattentive.

**Comment by bram85** [comment]
I agree that the image is misleading, AFAIK it does not match the original spec. The creation date is always optional, even when the task has been completed.
