### ISSUE TITLE
[feature idea] Allow for an “or” in the filters

### ISSUE THREAD

**Issue by Ekleog** [bram85/topydo#228]
If I read correctly filter documentation, it's only possible to do “and” and ”not”. Allowing parenthesis and “or” would make it possible to have more generic filters (like, `@home OR @specific-papers`, for the one use case I wanted to do).

Obviously it's always possible to just add the `@home` tag aside all `@specific-papers` tags, but it's redundant and requires more mental awareness than strictly required, so I think such a feature would be useful.

What do you think about it?

**Comment by mruwek** [comment]
It's a duplicate of #177

**Comment by Ekleog** [comment]
Oh, didn't notice, thanks!
