### ISSUE TITLE
Refresh UI after waking from sleep

### ISSUE THREAD

**Issue by jbrodriguez** [bram85/topydo#241]
Hi, new to topydo, awesome tool.

The title says it all, is it possible topydo detects it's waking up from sleep to refresh the UI, as to update due dates.

Alternatively, I haven't found a way to trigger a UI refresh manually.

Looked into https://www.topydo.org/#ColumnKeyMap and https://www.topydo.org/#ColumnShortcuts, but no luck.

Thanks !

**Comment by mruwek** [comment]
Although it is not documented in **topydo** `<CTRL>-L` should work for you as it is default shortcut for manual redraw in [urwid](http://urwid.org/reference/constants.html#urwid.REDRAW_SCREEN)

**Comment by jbrodriguez** [comment]
Thanks !!

I'm on a mac and it doesn't seem to work, but I'll look into urwid.

**Comment by jbrodriguez** [comment]
Hi, I tried it again after waking up from sleep and it does work.

Thanks a lot for the tip !
