### ISSUE TITLE
Continued availability of topydo documentation

### ISSUE THREAD

**Issue by RonCam** [bram85/topydo#254]
Topydo is very feature-rich and I constantly refer to the documentation, both here and on rawgit.

I note there hasn't been (is this correct?) developer-activity here for about a year, and rawgit is winding down its service.  May we have a heads-up if there's an end date in sight, for either of these resources?  Are there plans for preserving the documentation currently hosted on rawgit?  

Would it be advisable for Topydo users to make plans to store the documentation off-line in the foreseeable future?  Or not?

Thanks again for a great program!

**Comment by jbweston** [comment]
Seems that @bram85 has gone completely dark [since April](https://github.com/bram85).

They listed their website on their GitHub profile, but there's nothing actually there. I just fired off an email to the address they listed in the hope that they still check that mailbox (the message hasn't bounced yet, at least).

For reference here's what I sent:

```
Hi,

First off, thanks for creating topydo. I've only been using it for a few
months, but it's already improved my life a whole bunch.

I'm sending you this message because there hasn't been much activity on
the repo recently. I also see that you haven't been on GitHub in nearly
a year.

It seems like there are still a bunch of people who use topydo and it
would be a shame if it would die. Would you be open to passing on the
maintainership of the project to a willing member of the community? I
think the process could be as simple as creating an issue on GitHub and
asking for volunteers; I'm sure there would be some interest.

Thanks,
Joe
```

**Comment by mrshu** [comment]
@jbweston thanks a ton for trying to contact @bram85 -- I also believe there are quite a few users of `topydo` (myself included) who would be willing to lend a hand with maintaining it in the future.

In the absolute worst case scenario, given the GPL license `topydo` is distributed under, I believe the next course of action may be to just fork the project into something like `topydo-ng` in order to support its  continuous development.Still, I would much prefer @bram85 to continue working on `topydo`

**Comment by mruwek** [comment]
Hey, guys I exchanged some correspondence with @bram85 and he perfectly knows that documentation needs new home. Just give him a bit more time. Please remember that this project was always **spare time** one, and it just so happens that everyone has periods in his/hers life when such thing like *spare time* simply doesn't exist.

**Comment by mrshu** [comment]
@mruwek Absolutely, I believe we all understand that.

My point (and I believe @jbweston sees it in a similar way) was that there are people happy to help.

**Comment by RonCam** [comment]
Much appreciated, if anyone could provide a working link to replace this one, as shown in the line below?

_A static / downloadable copy of the documentation can be found at  [https://www.topydo.org/static.html](https://www.topydo.org/static.html) ._ 

Following the current link gives this error message (in Firefox) and, of course, no download:

**Secure Connection Failed**
An error occurred during a connection to www.topydo.org. SSL peer has no certificate for the requested DNS name. Error code: SSL_ERROR_UNRECOGNIZED_NAME_ALERT

**Comment by ranebrown** [comment]
This works for me https://cdn.rawgit.com/bram85/topydo/master/doc/Documentation.html

**Comment by RonCam** [comment]
Thanks to everyone and especially @bram85 (in a different thread) for answering the question in the original post.  And that is, no, it's not necessary to make off-line copies of topydo documentation.  It will continue to be available for the foreseeable future.

**Comment by RonCam** [comment]
Some time has passed, and I'm unable to find the currently-working URL for the documentation.  Has the move been completed, and if so, to where?

**Comment by RonCam** [comment]
For anyone following this thread, as of this time, topydo users should rely on the _Waybackmachine_ to access an archived copy of the program's documentation.  If anyone knows of a more recent copy than may be found there, please post the link!

**Comment by RonCam** [comment]
For anyone following this thread, as of this time, topydo users should rely on the _Waybackmachine_ to access an archived copy of the program's documentation.  If anyone knows of a more recent copy than may be found there, please post the link!
