### ISSUE TITLE
Prefer local todo.txt to global one

### ISSUE THREAD

**Issue by maxigaz** [bram85/topydo#295]
When I run `topydo` in a directory where `todo.txt` exists, I'd like that file to be browsed; otherwise, I'd like to use the one that's set in `~/.config/topydo/config`.

Is it possible to do this purely from topydo?

---

I've been able to figure out a workaround with a shell alias that partially works. This is what I put in my `.zshrc`:

```sh
alias topydo="[[ -f todo.txt ]] && { echo \"Browsing local todo.txt\n\"; topydo -t todo.txt -d done.txt } || topydo"
```

And here's the relevant part of my topydo config:

```
[topydo]
archive_filename = /path/to/my/notes/done.txt
filename = /path/to/my/notes/todo.txt
```

However, this solution doesn't work with subcommands like `columns` or options like `-h`.

**Comment by maxigaz** [comment]
Another idea I can think of is turning the alias into a function, and reference the argument as a variable.

```sh
topydo() {
	if [[ -f todo.txt ]]; then
		echo \"Browsing local todo.txt\n\"
		topydo -t todo.txt $1
	else
		topydo $1
	fi
}
```

Running this results in an error, however:

```
topydo:6: maximum nested function level reached; increase FUNCNEST?
```

**Comment by bram85** [comment]
Either rename your function or reference the topydo executable by its full path. Because now you have an infinite recursive function.
