### ISSUE TITLE
Direct todo.txt editing with $EDITOR doesn't work in prompt-mode

### ISSUE THREAD

**Issue by mruwek** [bram85/topydo#33]
```
topydo prompt
topydo> ls
topydo> edit
```

Add, remove or modify some todos in `$EDITOR`.

```
topydo> ls
```

Result: nothing has changed.

I tried adding `self.todolist.set_dirty()` before calling the editor, but it didn't work. CLI-mode (`topydo edit`) is not affected by this bug. I believe we need to do some sort of todo.txt reload in this case with prompt-mode.

**Comment by bram85** [comment]
I took a different (more generic) approach in commit 8eff0f0.
