### ISSUE TITLE
Path relative to ~ not accepted

### ISSUE THREAD

**Issue by robertvanbregt** [bram85/topydo#37]
If you provide a path to a filename starting with `~` (e.g. `~/todo.txt`) topydo will not do anything. Only a full path will work (`/User/<user>/todo.txt`)

(In stable version 0.3.2 using Mac OS X 10.9.5)

I will submit a pull request.

**Comment by robertvanbregt** [comment]
If I add `os.path.expanduser` to `todotxt()` in Config.py, the path is not expanded. :(

    def todotxt(self):
        return os.path.expanduser(self.cp.get('topydo', 'filename'))

    def archive(self):
        return os.path.expanduser(self.cp.get('topydo', 'archive_filename'))

**Comment by bram85** [comment]
Thanks for pointing out.

I'm puzzled why the call to `expanduser()` doesn't work from Config.py. I tried it myself (on Linux) and it works for me. That is when I put this in my configuration file:

```
filename = ~/todo.txt
```

To me the snippet you posted above seems to be the correct fix.

Pull request #38 is not complete, because `Config.todotxt()` and `Config.archive()` are called from multiple places, not just from `Main.py` where you addressed the issue (`EditCommand` also calls these functions).

So I need a bit more information why the solution above doesn't work for you.

**Comment by mruwek** [comment]
> To me the snippet you posted above seems to be the correct fix.

Same here.

Could You apply this snippet again to `Config.py` and test it in interactive python shell and show the output here? For example

```
>>> from topydo.lib.Config import config
>>> a = config()
>>> a.todotxt()
```

**Comment by robertvanbregt** [comment]
Todo.txt:

    $ cat ~/.todo.txt
    Buy milk 
    Polish shoes
    Do laundry

Config:

    $ cat ~/.topydo
    [topydo]
    filename = ~/todo.txt

Git:

    $ git status
    On branch stable
    Your branch is up-to-date with 'origin/stable'.
    nothing to commit, working directory clean 

Python:

    $ python
    >>> from topydo.lib.Config import config
    >>> a = config()
    >>> a.todotxt()
    '~/todo.txt'

Snippet applied:

    $ python
    >>> from topydo.lib.Config import config
    >>> a = config()
    >>> a.todotxt()
    '/Users/robert/todo.txt'

Works as expected.

When I run `python topydo/cli/Main.py` to try the snippet in the application, I get an error message:

	Traceback (most recent call last):
	  File "topydo/cli/Main.py", line 83, in <module>
		from topydo.lib.Config import config, ConfigError
	ImportError: No module named topydo.lib.Config

I'm no Python guru, so I don't know how to get past this.

(this is all done on my macbook on OS X 10.8.5 running python 2.7.2)

	Python 2.7.2 (default, Oct 11 2012, 20:14:37) 
	[GCC 4.2.1 Compatible Apple Clang 4.0 (tags/Apple/clang-418.0.60)] on darwin
	Type "help", "copyright", "credits" or "license" for more information.

**Comment by robertvanbregt** [comment]
note to self: `export PYTHONPATH=/Users/robert/code/topydo` did the trick :-)

    $ python topydo/cli/Main.py
    |  1| Buy milk
    |  2| Polish shoes
    |  3| Do laundry

I will update my code for the fix and issue an updated PR.
