### ISSUE TITLE
Add strict option for do command to configuration

### ISSUE THREAD

**Issue by robertvanbregt** [bram85/topydo#41]
**Enhancement:**
Add a `strict` option for the [do command](https://github.com/bram85/topydo/wiki/do-%28subcommand%29) to the [Configuration](https://github.com/bram85/topydo/wiki/Configuration).
Also make sure that the command line can overwrite any `strict` setting from the configuration file.

**Rationale:**
I prefer my recurring items being based on the actual due date, not the completion date.

**Suggested implementation:**

* Add section `[do]` to config
* Add item `strict` to section with possible values of `0` or `1` and default `0`
* Add support for `--loose` flag to do command. For backwards compatibility this is the default (if neither loose or strict is specified on the command line). Flags are [mutually exclusive](https://docs.python.org/2/library/argparse.html#mutual-exclusion)
* When executing do command:
    * If configuration is set, apply flag (or default if none specified)
    * If `--strict` flag is provided from the command line, overwrite configuration of `strict = 0`
    * If `--loose` flag is provided from the command line, overwrite configuration of `strict = 1`

**Comment by mruwek** [comment]
I believe that with d7d40205db9537cf4cd06fdf4742827cc2f0aaba this issue is no longer valid, as ability to specify strict/loose recurrence on a per-item basis (rec: vs rec:+) is superior to any config option.

**Comment by bram85** [comment]
Agreed.
