### ISSUE TITLE
Disable auto-archive

### ISSUE THREAD

**Issue by robertvanbregt** [bram85/topydo#42]
### Disable auto-archive and manually archive

The default for topydo is, to automatically archive completed tasks to the archive file. 

Rationale:
To be able to undo a completion (for example), it should be possible to configure the application to not have this behaviour.

The historical todotxt shell scripts supported this by a `-a` flag and most GUI 
applications support this feature, too.

This could be implemented in topydo like this:
* Add command line options -a (short) and --no-archive (long) to prevent 
  auto archiving
* Add item `archive` to section [topydo] in configuration file
    * Supports values `0` and `1`, default = 1
* On execution of do command:
  * If auto-archive is off then do not move completed item to archive file   
* Add `archive` command to explicitly move completed items to archive file

(Bonus feature could be a command to 'undo' an item)

**Comment by bram85** [comment]
In the master branch you can disable it with the following configuration:

```ini
[topydo]
archive_filename =
```

You can also use this per call with the `-a` flag:

    topydo -a do 1

Note, however, that if you have archiving enabled it would be archived anyway with the next `do` invocation without `-a` flag.

Jacek is also working on an `undo` command (see PR #47).

**Comment by robertvanbregt** [comment]
:+1:
