### ISSUE TITLE
Expression with negation does not work with multicommands

### ISSUE THREAD

**Issue by bram85** [bram85/topydo#51]
Negation is used with `ls` to filter out certain todo items. This does not work with other commands that can operate on multiple todo items at the same time, e.g. `edit`:

```bash
topydo edit -x -e -due:
```

Result:

```bash
option -u not recognized
Invalid todo number given: -e.
Invalid todo number given: -due:.
```

**Comment by mruwek** [comment]
`topydo ls -@test`

Result:
`option -@ not recognized`

The list is printed as demanded though.

**Comment by bram85** [comment]
Ah, at least something works :) (projects and contexts). Filtering arbitrary texts/tags seems to fail. I'll try to have a stab at it.

**Comment by mruwek** [comment]
`topydo ls -x -due:`

gives:

`option -d not recognized`

But list is printed as demanded.

**Comment by bram85** [comment]
Seems that `ls` can handle it more or less, `do`, `edit`, etc. are broken.

**Comment by mruwek** [comment]
Yet another observation:

`topydo ls @test -due:`

works as expected without any error. The only difference with call above is `@test` which separates command name from minus sign and topydo then doesn't treat `-due:` as an option. I'm quite sure now that the problem lies in our usage of getopt.

**Comment by mruwek** [comment]
> `do`, `edit`, etc. are broken.

It's more complicated then that.

```
mruwek@opti77 ~ $ topydo add -f - <<END
test @test
test @test @test2
test @test due:tom
END

|bat| 2015-09-23 test @test
|wa2| 2015-09-23 test @test @test2
|bau| 2015-09-23 test @test due:2015-09-24

mruwek@opti77 ~ $ topydo postpone -e @test -@test2 -due: tod
|bat| 2015-09-23 test @test due:2015-09-23

mruwek@opti77 ~ $ topydo pri -e @test -@test2 D
Priority set to D.
|bat| (D) 2015-09-23 test @test due:2015-09-23
Priority set to D.
|bau| (D) 2015-09-23 test @test due:2015-09-24

mruwek@opti77 ~ $ topydo edit -e @test -@test2
|bat| (D) 2015-09-23 test @test due:2015-09-23
|bau| (D) 2015-09-23 test @test due:2015-09-24

mruwek@opti77 ~ $ topydo edit -e -@test2 @test
option -@ not recognized
Invalid todo number given: -e.
Invalid todo number given: -@test2.
Invalid todo number given: @test.

mruwek@opti77 ~ $ topydo pri -e -@test2 @test C
option -@ not recognized
Invalid todo number given: -e.
Invalid todo number given: -@test2.
Invalid todo number given: @test.

mruwek@opti77 ~ $ topydo pri -e @test -@test2 C
Priority changed from D to C
|bat| (C) 2015-09-23 test @test due:2015-09-23
Priority changed from D to C
|bau| (C) 2015-09-23 test @test due:2015-09-24
```

As You can see - if **first** part of expression is *positive* (doesn't begin with minus sign) everything works splendidly. Bug happens only if the first part (or the lonely part) of expression is negation. Then `getopt` treats it as an option and not as an expression and consequently shows an error.

**Comment by mruwek** [comment]
Ok. So **it's not** a bug.

As I wrote before: this thing is caused by [getopt](https://docs.python.org/2/library/getopt.html#getopt.getopt):

> **Note:** Unlike GNU `getopt()`, after a non-option argument, all further arguments are considered also non-options. This is similar to the way non-GNU Unix systems work.

And there is really no need to fix that behavior. All we need is reminding to user that he/she has to use `--` (double hyphen) if he/she wants to use negation as first argument.

Example:

**Bad:** `topydo ls -due:`
**Good:** `topydo ls -- -due:`

**Bad:** `topydo edit -e -due:`
**Good:** `topydo edit -e -- -due:`

**Comment by mruwek** [comment]
Also, I think we shall terminate further execution of command if there is some unrecognizable option.

**Comment by bram85** [comment]
I think this has been properly addressed on this [wiki page](https://github.com/bram85/topydo/wiki/Filter-expressions#negation-and-flags).
