### ISSUE TITLE
Wheel installation issues (dependencies)

### ISSUE THREAD

**Issue by MinchinWeb** [bram85/topydo#79]
I believe this issue is caused by bbdfb2a5ce72cf0ce069983b33467f6a8cdd6609.

When installing from wheels, no code is executed (at install time). Thus, code that conditionally determines which dependencies are required will be run when the wheel is generated, rather than when the wheel is installed.

By way of example, I am installing `topydo 0.7.0` on my local machine (Win 10, Python 3.5) from [PyPI](https://pypi.python.org/pypi/topydo/0.7). I would expect that *six*, *arrow*, and *colorama* would be installed. Instead, I got *ushlex*, *six*, *python-dateutil*, *arrow*, and *backports.shutil-get-terminal-size*.

```
(env2) C:\temp>pip install topydo
Collecting topydo
  Downloading topydo-0.7-py2.py3-none-any.whl (89kB)
    100% |################################| 90kB 649kB/s
Collecting ushlex (from topydo)
  Downloading ushlex-0.99.tar.gz
Collecting six>=1.9.0 (from topydo)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting arrow>=0.7.0 (from topydo)
Collecting backports.shutil-get-terminal-size>=1.0.0 (from topydo)
  Downloading backports.shutil_get_terminal_size-1.0.0-py2.py3-none-any.whl
Collecting python-dateutil (from arrow>=0.7.0->topydo)
  Using cached python_dateutil-2.4.2-py2.py3-none-any.whl
Installing collected packages: ushlex, six, python-dateutil, arrow, backports.shutil-get-terminal-size, topydo
  Running setup.py install for ushlex
Successfully installed arrow-0.7.0 backports.shutil-get-terminal-size-1.0.0 python-dateutil-2.4.2 six-1.10.0 topydo-0.7 ushlex-0.99

(env2) C:\temp>python --version
Python 3.5.0
```

Possible solutions include not providing wheels, or at least not universal wheels, or using `extra_requires` (available since `wheel 0.24`, see [here](http://stackoverflow.com/questions/23280850/conditional-dependency-with-python-wheels) and [here](https://wheel.readthedocs.org/en/latest/))

**Comment by bram85** [comment]
Thanks for reporting.

I think my plan of action will be to revert commit bbdfb2a5ce72cf0ce069983b33467f6a8cdd6609 and only provide wheels from now on.

**Comment by bram85** [comment]
Fixed in 0.8, only providing wheels (for now).

**Comment by MinchinWeb** [comment]
Installing from `pip` seems to be working with v0.8. :+1:

**Comment by bram85** [comment]
Glad to hear that, sorry about the mess with 0.7.
