### ISSUE TITLE
Option to add a completed item

### ISSUE THREAD

**Issue by kmac** [bram85/topydo#82]
This might sound ridiculous, but I would find it useful to be able to add an item and mark it as complete at the same time. The use-case is to allow for an item that comes up and is immediately handled, but can then be recorded for tracking purposes.

It might be handled via a new flag to the add command, say `-d`:

    topydo add -d "Something I just did, confirmation number 12345678"

**Comment by bram85** [comment]
You can also use `topydo add "x 2015-11-26 I did this"` which already works.

Is that sufficient for you?

**Comment by kmac** [comment]
Good idea, I wasn't sure if that would work. I created a function for it:

    t-add-done() { topydo add "x $(date +%Y-%m-%d) $*" }

Closing this off. Thanks!
