### ISSUE TITLE
Filter on complete date?

### ISSUE THREAD

**Issue by yijia-zhan** [bram85/topydo#86]
First thank you for the project! I only started using it not too long ago and it has become something I can't live without now. 

Just wondering if there's a `ls` command that allows me to filter on complete date? Similar to the `due:tomorrow` filter, is there a way to acommopish something similar to `topydo ls complete:yesterday`?

**Comment by bram85** [comment]
It's not possible right now with topydo, for now you're bound to good ol' `grep(1)`.

But your request is valid, I have similar thoughts about querying for creation date, which also requires a special tag.

One complication with the completion date is that not all to-do items are in memory when you auto-archive items, these items are not read. For performance reasons I'd prefer not to load completed items upon each invocation of topydo, so I have to think about it for a bit.

**Comment by bram85** [comment]
You can filter on completion (and creation) date now in the master branch. If you use auto-archiving, then there are no completed items in your todo.txt file, but in your done.txt file. So, invoke `topydo` like this:

    topydo -t done.txt ls complete:yesterday

**Comment by bram85** [comment]
Not just available in master, just update to version 0.9 ;)
